plugins {
    id 'java-library'
    id 'eclipse'
    id 'maven-publish'
    id 'idea'
    alias libs.plugins.modDevGradle
}

String buildNumber = System.getenv('GITHUB_RUN_NUMBER')
String buildType = System.getenv('BUILD_TYPE') ?: 'build'
String githubRef = System.getenv('GITHUB_REF')
if (githubRef != null && githubRef.startsWith('refs/tags/')) {
    version = githubRef.substring(githubRef.lastIndexOf('/') + 1)
} else {
    version = "${mod_version}" + (buildNumber != null ? "+${buildType}.${buildNumber}" : '')
}
group = maven_group

sourceSets {
    gameTest {
        compileClasspath += sourceSets.main.output + sourceSets.main.compileClasspath
        runtimeClasspath += sourceSets.main.output + sourceSets.main.runtimeClasspath
    }
}

configurations {
    gameTestImplementation.extendsFrom implementation
    gameTestCompileOnly.extendsFrom compileOnly
    gameTestRuntimeOnly.extendsFrom runtimeOnly
}

apply from: "$rootDir/gradle/scripts/moddevgradle.gradle"
apply from: "$rootDir/gradle/scripts/repositories.gradle"
apply from: "$rootDir/gradle/scripts/jars.gradle"
apply from: "$rootDir/gradle/scripts/publishing.gradle"
apply from: "$rootDir/gradle/scripts/resources.gradle"
apply from: "$rootDir/dependencies.gradle"

java.toolchain.languageVersion = JavaLanguageVersion.of(java_version as int)
compileJava.options.encoding = 'UTF-8'

sourceSets.main.resources {
    srcDir 'src/generated/resources'
    exclude '.cache/**'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
